### ISSUE TITLE
remove projects page, just use home page?

### ISSUE THREAD

**Issue by bqpd** [convexengineering/convexengineering.github.io#4]
@1ozturkbe what do you think of removing the projects page for now so that there's just one place to keep up to date?

**Comment by 1ozturkbe** [comment]
I am down, but how about the posts/pictures there? I think the website looks really bland without them. Also, people are averse to scrolling a lot, aren't they? The bottom of the page just might not get visited.

**Comment by bqpd** [comment]
good points both
