### ISSUE TITLE
Redirect http://hoburg.mit.edu/ to http://convex.mit.edu/

### ISSUE THREAD

**Issue by bqpd** [convexengineering/convexengineering.github.io#7]
in https://github.com/convexengineering/gpkit/issues/1249, @mayork said:

> @bqpd @whoburg @1ozturkbe @mjburton11 when I google any of our publications the hoburg.mit.edu result is way above the convex.mit.edu result. Can we make it so that when you access hoburg.mit.edu you're redirected to convex.mit.edu? (sorry for making this a gpkit issue, I couldn't figure out how to make an issue in the website repo)

**Comment by whoburg** [comment]
yep, this is fine with me. Anyone see any downsides? Are my permissions needed to make it happen?

**Comment by bqpd** [comment]
I just made the change! The hoburg homepage is now a redirect...papers that have the same name in both are already linked, and the rest will migrate over once google catches up.
